base:
    seed: &seed 42
model:
    type: Qwen2VL
    path: /home/ubuntu/.cache/huggingface/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/51c47430f97dd7c74aa1fa6825e68a813478097f
    torch_dtype: auto
calib:
    name: pileval
    download: False
    path: ../datasets/data_calib/pileval
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: [wikitext2, c4]
    download: False
    path: ../datasets/data_eval
    bs: 1
    inference_per_block: False
    seq_len: 2048
quant:
    method: Awq
    weight:
        bit: 2
        symmetric: False
        granularity: per_group
        group_size: 128
        calib_algo: learnable
    special:
        trans: True
        weight_clip: True
        save_scale: True
        clip_version: v1
        scale_path: ../cache/activations/Q2VL_7b/awq_w2g128
        save_clip: False
        clip_path: ../cache/activations/Q2VL_7b/awq_w2g128
save:
    save_path: ../models/Qwen2_VL_AWQ
    save_lightllm: False
    save_vllm: False
    save_trans: True
    save_fake: True