base:
    seed: &seed 42
model:
    type: Qwen2VL
    path: /home/ubuntu/.cache/huggingface/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/51c47430f97dd7c74aa1fa6825e68a813478097f
    torch_dtype: auto
calib:
    name: wikitext2
    download: False
    n_samples: 512
    path: datasets/data_calib/wikitext2
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [transformed, fake_quant]
    name: [wikitext2, c4]
    download: False
    path: datasets/data_eval
    bs: 1
    seq_len: 2048
    inference_per_block: False
quant:
    method: TesseraQ
    weight:
        bit: 2
        symmetric: False
        granularity: per_group
        group_size: 128
        calib_algo: minmax
    special:
        lr: 0.001
        iterations: 250
        wd: 0.0
        batch_size: 4
        deactive_amp: False
        aug_loss: False
        optimize_scale: True
        scale_lr: 0.001
        thresholds: [0.8, 0.65, 0.5, 0.43, 0.38, 0.34, 0.3, 0.27, 0.24, 0.21, 0.18, 0.15, 0.12, 0.10, 0.08,
                      0.06, 0.04, 0.02, 0.01, 0.005]
        weight_clip: True
        load_transform: True
        clip_version: v1
        reduce_memory: False
        scale_path: cache/activations/Q2VL_7b/awq_w2g128
        clip_path: cache/activations/Q2VL_7b/awq_w2g128
    quant_out: True
save:
    save_path: ../models/Qwen2VL
    save_fp: False
    save_trans: True
    save_fake: True
    save_lightllm: False
    save_autogptq: False
    save_vllm: False